project_id = "cysnnnobeumculzzhttv"

[functions.create-checkout]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.create-promotion-checkout]
verify_jwt = true

[functions.verify-promotion-payment]
verify_jwt = true

[functions.create-ad-checkout]
verify_jwt = true

[functions.verify-ad-payment]
verify_jwt = true

[functions.ad-assistant]
verify_jwt = true
