project_id = "cysnnnobeumculzzhttv"

[functions.create-checkout]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.create-promotion-checkout]
verify_jwt = true

[functions.verify-promotion-payment]
verify_jwt = true
